# Minimal Theme Configuration for PrestaShop
name: minimal-theme
display_name: Minimal Theme
version: 1.0.0
author:
  name: "PrestaShop Team and Contributors"

meta:
  compatibility:
    from: 9.0.0
    to: ~9.9.9
    framework: your-framework-name

  available_layouts:
    layout-custom:
      name: Custom Layout
      description: You custom layout.

global_settings:
  image_types:
    cart_default:
      width: 125
      height: 125
      scope: [products]
    small_default:
      width: 98
      height: 98
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 452
      height: 452
      scope: [products, manufacturers, suppliers]
    large_default:
      width: 800
      height: 800
      scope: [products, manufacturers, suppliers]
    home_default:
      width: 250
      height: 250
      scope: [products]
    category_default:
      width: 180
      height: 180
      scope: [categories]

theme_settings:
  default_layout: layout-custom
